import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { AppInfo } from "@/lib/cv/docx";
import { SECTION_INTROS, SECTION_LABELS } from "@/lib/interview/bank";
import type { QuestionSet } from "@/lib/interview/select";
import { FONT, FONT_BOLD, FONT_ITALIC, pt } from "./shared";

/* Mirrors src/lib/cv/docx/interviewQuestions.ts — same sections, same order,
   same ruled space, so the two formats are the same worksheet. */
const s = StyleSheet.create({
  page: {
    paddingTop: 48, paddingBottom: 54, paddingHorizontal: 50,
    fontFamily: FONT, fontSize: pt(20), color: "#1a1a1a", lineHeight: 1.4,
  },
  title: { fontFamily: FONT_BOLD, fontSize: pt(40), marginBottom: 3 },
  role: { fontFamily: FONT_BOLD, fontSize: pt(24), marginBottom: 2 },
  meta: { fontSize: pt(18), color: "#5a6072", marginBottom: 20 },

  sectionHead: {
    fontFamily: FONT_BOLD, fontSize: pt(22), marginTop: 18, paddingBottom: 3,
    borderBottomWidth: 0.7, borderBottomColor: "#c9cfdd",
  },
  sectionIntro: { fontSize: pt(18), fontFamily: FONT_ITALIC, color: "#555555", marginTop: 5, marginBottom: 8 },

  question: { fontFamily: FONT_BOLD, fontSize: pt(20), marginTop: 10 },
  prompt: { fontSize: pt(17), fontFamily: FONT_ITALIC, color: "#666666", marginTop: 2 },
  rule: { borderBottomWidth: 0.6, borderBottomColor: "#c9cfdd", marginTop: 11 },

  footer: {
    position: "absolute", bottom: 26, left: 50, right: 50,
    textAlign: "center", fontSize: pt(16), color: "#888888",
  },
});

function AnswerLines({ count }: { count: number }) {
  return (
    <View>
      {Array.from({ length: count }, (_, i) => (
        <View key={i} style={s.rule} />
      ))}
    </View>
  );
}

export function InterviewQuestionsDocument({ set, info }: { set: QuestionSet; info: AppInfo }) {
  const today = new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });

  /* Numbering derived without mutation — a counter reassigned inside render is
     unsafe if React re-renders a subtree, and the compiler rejects it. */
  const blocks = set.sections.filter((block) => block.questions.length > 0);
  const startAt = blocks.map((_, i) =>
    blocks.slice(0, i).reduce((n, b) => n + b.questions.length, 0),
  );
  const numbered = blocks.map((block, bi) => ({
    section: block.section,
    questions: block.questions.map((q, i) => ({ ...q, number: startAt[bi] + i + 1 })),
  }));

  return (
    <Document title={`Interview questions — ${info.jobTitle} at ${info.companyName}`} author="TrackMyself">
      <Page size="A4" style={s.page}>
        <Text style={s.title}>Interview preparation</Text>
        <Text style={s.role}>{info.jobTitle} · {info.companyName}</Text>
        <Text style={s.meta}>
          {set.total} questions{info.location ? ` · ${info.location}` : ""} · prepared {today}
        </Text>

        {numbered.map((block) => (
          <View key={block.section}>
            <Text style={s.sectionHead}>{SECTION_LABELS[block.section].toUpperCase()}</Text>
            <Text style={s.sectionIntro}>{SECTION_INTROS[block.section]}</Text>

            {block.questions.map((q) => (
              <View key={`${block.section}-${q.number}`} wrap={false}>
                <Text style={s.question}>{q.number}. {q.text}</Text>
                {q.prompt ? <Text style={s.prompt}>{q.prompt}</Text> : null}
                <AnswerLines count={q.prompt ? 2 : 3} />
              </View>
            ))}
          </View>
        ))}

        <Text style={s.footer} fixed>Generated by TrackMyself</Text>
      </Page>
    </Document>
  );
}
