import { AlignmentType, BorderStyle, Document, Paragraph, TextRun } from "docx";
import type { AppInfo } from "./coverLetter";
import { FONT, pageMargin, txt } from "./shared";
import { SECTION_INTROS, SECTION_LABELS } from "@/lib/interview/bank";
import type { QuestionSet } from "@/lib/interview/select";

const RULE = {
  bottom: { style: BorderStyle.SINGLE, size: 4, color: "C9CFDD", space: 6 },
};

/* Blank ruled lines to draft an answer on. Underlined empty runs keep the rule
   visible in Word and LibreOffice without needing a table per question. */
function answerLines(count: number) {
  return Array.from({ length: count }, () =>
    new Paragraph({
      spacing: { before: 90, after: 0 },
      border: RULE,
      children: [txt(" ", { size: 18 })],
    }),
  );
}

export function buildInterviewQuestions(set: QuestionSet, info: AppInfo): Document {
  const today = new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });

  const body: Paragraph[] = [
    new Paragraph({
      spacing: { after: 40 },
      children: [txt("Interview preparation", { size: 40, bold: true })],
    }),
    new Paragraph({
      spacing: { after: 20 },
      children: [txt(`${info.jobTitle} · ${info.companyName}`, { size: 24, bold: true })],
    }),
    new Paragraph({
      spacing: { after: 240 },
      children: [
        txt(
          `${set.total} questions${info.location ? ` · ${info.location}` : ""} · prepared ${today}`,
          { size: 18, color: "5A6072" },
        ),
      ],
    }),
  ];

  let n = 0;

  for (const block of set.sections) {
    if (!block.questions.length) continue;

    body.push(
      new Paragraph({
        spacing: { before: 320, after: 40 },
        border: RULE,
        children: [txt(SECTION_LABELS[block.section].toUpperCase(), { size: 22, bold: true })],
      }),
      new Paragraph({
        spacing: { after: 160 },
        children: [txt(SECTION_INTROS[block.section], { size: 18, italics: true, color: "555555" })],
      }),
    );

    for (const q of block.questions) {
      n += 1;
      body.push(
        new Paragraph({
          spacing: { before: 160, after: 30 },
          children: [
            txt(`${n}. `, { size: 20, bold: true }),
            txt(q.text, { size: 20, bold: true }),
          ],
        }),
      );

      if (q.prompt) {
        body.push(
          new Paragraph({
            spacing: { after: 40 },
            children: [txt(q.prompt, { size: 17, italics: true, color: "666666" })],
          }),
        );
      }

      body.push(...answerLines(q.prompt ? 2 : 3));
    }
  }

  body.push(
    new Paragraph({
      spacing: { before: 400 },
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "Generated by TrackMyself",
          font: FONT,
          size: 16,
          color: "888888",
        }),
      ],
    }),
  );

  return new Document({
    creator: "TrackMyself",
    title: `Interview questions — ${info.jobTitle} at ${info.companyName}`,
    sections: [{ properties: pageMargin(1000, 1000, 1000, 1000), children: body }],
  });
}
